export interface ProductInterface {
  name: String,
  colors?: Array<string>,
  materials?: Array<string>,
  material_finitions?: Array<string>,
  thickness_choice?: Array<string>,
  width?: Number,
  weight?: Number,
  length?: Number,
  description?: String,
  main_image?: String,
  images?: Array<string>,
  category?: String,
  sub_category?: String,
  active?: Boolean,
  new_product?: Boolean,
  price_ht?: Number,
  tax?: Number,
  price_ttc?: Number,
  custom_measures?:Boolean,
  measure?: Array<string>
}